apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: todo-cloud-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: todo_db
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: postgres
